In [5]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from missingpy import KNNImputer
import copy
from sklearn.preprocessing import LabelEncoder;

In [6]:
df=pd.read_csv('train.csv')

In [7]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [8]:
# 80% of counts are 

class columnTypeIdentification:
    def __init__(self, df):
        self.dtypes={}
        self.df=df
        for i in self.df.columns:
            self.dtypes[i]=(self.df[i].dtypes)
#         print(self.dtypes)
        self.colTypes={'Categorical': [], 'Text':[], 'Numeric': []}
        self.detectingColTypes()
        target_type=''
        
        for i in self.colTypes.keys():
            if y in self.colTypes[i]:
                target_type=i
                break
        self.target_type=target_type
    
    def detectingColTypes(self):
        for i in self.dtypes.keys():
            if self.dtypes[i]=='O':
                if (df[i].fillna('',axis=0).apply(lambda x: len(x))).quantile(q=0.95)<20:
                    self.colTypes['Categorical'].append(i)
                else:
                    self.colTypes['Text'].append(i)
            else: 
                distinctValues = self.df[i].nunique()
                if distinctValues < int((self.df[i].shape[0])*0.05):
                    self.colTypes['Categorical'].append(i)
                else:
                    self.colTypes['Numeric'].append(i)

In [9]:
class nullHandling():
  
    def __init__(self, df):
        self.dict_isnull = (df.isnull().sum() / len(df)).to_dict()
        self.df=df
        self.colTypes=colTypes.copy()
 
    
    def remove_columns(self):
        cols_remove=[]
        for key in self.dict_isnull:
            if(self.dict_isnull[key]>0.75):
                cols_remove.append(key)        
        if not cols_remove:
            return self.colTypes
        else:
            for i in cols_remove:
                for j in self.colTypes.keys():
                    if i in self.colTypes[j]:
                        self.colTypes[j].remove(i)
        if y in cols_remove:
            cols_remove.remove(y)
        
        self.df.drop(cols_remove,axis=1, inplace=True)
        
#         return self.colTypes
        
    
    def continuous_impute_zero(self):
        df_temp=self.df.copy()
        df_temp[self.colTypes['Numeric']]=df_temp[self.colTypes['Numeric']].fillna(0)
        return df_temp
    
    def continuous_impute_mean(self):
        df_temp=self.df.copy()
        imputer = SimpleImputer(strategy='mean')
        df_temp[self.colTypes['Numeric']] = imputer.fit_transform(df_temp[self.colTypes['Numeric']])
        return df_temp
    
    def continuous_impute_knn(self):
        df_temp=self.df.copy()
        imputer = KNNImputer(n_neighbors=5) 
        df_temp[self.colTypes['Numeric']] = imputer.fit_transform(df_temp[self.colTypes['Numeric']])
        return df_temp
    
        
    def impute(self,strategy,fill_value = 0, fill_categorical = '-1'):
        df_temp=self.df
        
        #Dealing wit Continuous cols
        if strategy is None:
            df_temp[self.colTypes['Numeric']]=df_temp[self.colTypes['Numeric']].fillna(fill_value)
        elif strategy == 'mean':
            self.continuous_impute_mean()
        elif strategy == 'knn':
            self.continuous_impute_knn()
            
        #dealing with categorical Cols_temp[self.colTypes['Categorical']]=df_temp[self.colTypes['Categorical']].fillna(fill_categorical)
        
        return df_temp

In [10]:
class FeatureReduction:

    def __init__(self,df):
        self.df=df
        self.colTypes=copy.deepcopy(colTypes)

        self.colTypes[target_type].remove(y)
        self.all_dfs=[]
        self.pearsons_corr()
#removing the continuous column with a correlation of above 0.8
    def pearsonCorr(self):
        self.colTypes['Numeric']=set(self.colTypes['Numeric']).intersection(set(self.df.columns))
        corr=self.df[list(self.colTypes['Numeric'])].corr(method="pearson").abs()
        upper = corr.where(np.triu(np.ones(corr.shape), k=1).astype(np.bool))
        to_drop = [column for column in upper.columns if any(upper[column] > 0.80)]
        self.df.drop(to_drop, axis=1,inplace=True)
        self.colTypes['Numeric'] = [x for x in self.colTypes['Numeric'] if x not in to_drop]
        self.all_dfs.append(self.df)

        #returns the dict of dataframes updated in this class
    def returnDfs(self):
        return self.all_dfs

In [11]:
class Outlierhandling():
    def __init__(self,df):
        self.df=df.copy() 
        self.colTypes=copy.deepcopy(colTypes)
        
        self.colTypes[target_type].remove(y)
        
        self.colTypes['Numeric']= set(colTypes['Numeric']).intersection(set(df.columns))
        
        self.all_dfs=[]
        self.capping_outlier() 
     #   self.remove_outlier()
        self.zscore_outlier()
      
    def capping_outlier(self,lowerperc = 0.01,higherperc = 0.99):
        df = self.df[list(self.colTypes['Numeric'])].copy()
        df_out = self.df
        for col in df.columns:
            percentiles = df[col].quantile([lowerperc,higherperc]).values
            df[col][df[col] <= percentiles[0]] = percentiles[0]
            df[col][df[col] >= percentiles[1]] = percentiles[1]
            df_out[list(self.colTypes['Numeric'])] = df
        self.all_dfs.append(df_out)
    
    
    def remove_outlier(self):
        df_out=self.df[list(self.colTypes['Numeric'])].copy()
        df_in = self.df.copy(deep=True)
        df_in.drop(list(self.colTypes['Numeric']),axis=1,inplace=True)
        for col_name in df_out.columns:
            q1 = df_out[col_name].quantile(0.25)
            q3 = df_out[col_name].quantile(0.75)
            iqr = q3-q1
            lower = q1-1.5*iqr
            upper = q3+1.5*iqr
            df_out = df_out.loc[(df_out[col_name] > lower) & (df_out[col_name] < upper)]
            df_final = pd.concat([df_in,df_out],axis = 1,join='inner')           
        self.all_dfs.append(df_final)
    
    
    def zscore_outlier(self,threshold = 3):
        l = []
        df1=self.df.copy(deep=True)
        df = self.df[list(self.colTypes['Numeric'])].copy(deep=True)
        df1.drop(self.colTypes['Numeric'],axis=1,inplace=True)
        df_out = pd.DataFrame()
        for i in df.columns:
            temp = []
            mean_1 = np.mean(df[i])
            std_1 =np.std(df[i])  
            for y in df[i]:
                z_score= (y - mean_1)/std_1 
                if np.abs(z_score) < threshold:
                    temp.append(y)
            df_temp = pd.DataFrame(temp)
            l.append(df_temp)
        df_out = pd.concat(l,axis = 1,join = 'inner')
        df_out.columns = df.columns
        df_final = pd.concat([df1,df_out],axis = 1,join='inner')  
        self.all_dfs.append(df_final)
    
    
    
    def return_dfs(self):
        return self.all_dfs

In [12]:
class Encoding:

    def __init__(self,df):
        self.colTypes=copy.deepcopy(colTypes)
#fetching column types for the columns in the current df
        self.colTypes['Categorical'] = set(df.columns).intersection(set(colTypes['Categorical']))
#removing the target column for the list of categorical columns
        if y in self.colTypes['Categorical']:
            self.colTypes['Categorical'].remove(y)
            
        self.df=df.copy()
        self.all_dfs = []
        self.oneHotEncode()
        self.labelEncode()
        
#encoding the categorical columns exclusing the target column
    def oneHotEncode(self):
        df1=self.df.copy(deep=True)
        df_y=pd.DataFrame()
        df1=pd.get_dummies(df1,drop_first=True,columns=list(self.colTypes['Categorical']))
        self.all_dfs.append(self.targetEncode(df1))

#encoding the categorical columns exclusing the target column
    def labelEncode(self):
        df1=self.df.copy(deep=True)
        df_y=pd.DataFrame()
        for x in self.colTypes['Categorical']:
            df1[x] = LabelEncoder.fit_transform(df1, y=df1[x])
        self.all_dfs.append(self.targetEncode(df1))

#encoding the categorical target column
    def targetEncode(self,t_df):
        if y not in self.colTypes['Numeric']:
             t_df[y] = LabelEncoder.fit_transform(t_df, y=t_df[y])
        return t_df
       
#returns the dict of dataframes updated in this class
    def returnDfs(self):
        return self.all_dfs

In [13]:
y='Survived'
#Col Indentification
colIdentObj=columnTypeIdentification(df)
colTypes=colIdentObj.colTypes
target_type=colIdentObj.target_type


#Null handling
nullHndlngObj=nullHandling(df)


# colTypes=nullHndlngObj.remove_columns()
df_dict={}
for strategy in [None, 'mean', 'knn']:
    df_dict['null_strategy_'+str(strategy)] = nullHndlngObj.impute(strategy)


#Feature Reduction
df_all=[]
for i in df_dict.keys():
    fRdctionObj=FeatureReduction(df_dict[i])
    df_all.extend(fRdctionObj.return_dfs())


#Outlier handling
df_all_oh=[]
for i in df_all:
    OH=Outlierhandling(i)
    df_all_oh.extend(OH.return_dfs())
    
    
#Encoding columns    
df_all_en=[]
for i in df_all_oh:
    en=Encoding(i)
    df_all_en.extend(en.return_dfs())    

    
    
#output of EDA : df_all_en

C:\Users\SirajuddinMohammed\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\SirajuddinMohammed\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\SirajuddinMohammed\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\SirajuddinMohammed\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:236: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.classes_, y = _encode(y, encode=True)

In [14]:
colTypes['Numeric']

['PassengerId', 'Age', 'Fare']